modLoader="javafml"
loaderVersion="[56,)"
license="MIT License"
[[mods]]
modId="spawncapcontrolutility"
version="${file.jarVersion}"
displayName="Spawncap Control Utility"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spawncap-control-utility"
displayTest="IGNORE_SERVER_VERSION"
updateJSONURL="https://github.com/mactso/spawncapcontrolutility/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='spawncapcontrolutility.'
[[dependencies.spawncapcontrolutility]]
    modId="forge"
    mandatory=true
    versionRange="[56,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.spawncapcontrolutility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.6,1.22)"
    ordering="NONE"
    side="SERVER"
# side="BOTH", "CLIENT?", "SERVER"

